### ISSUE TITLE
Lightzone crashes on scanning a directory for pictures

### ISSUE THREAD

**Issue by meisam** [Aries85/LightZone#124]
I am running LighZone on xubunt 14.04 with Oracle/Sun Java 1.7.0_60, and gcc 4.8.2
. LightZone crashes when it scans a directory for pictures. This happens both on the binary files downloaded form the LighZone project website and from on the latest commit on the master branch. The 4.1.0~beta9 (441f3c6) commit seems to be working fine.

This is the stack trace
java.lang.NoClassDefFoundError: Could not initialize class com.lightcrafts.utils.xml.XMLUtil
    at com.lightcrafts.image.types.JPEGImageType.getXMP(JPEGImageType.java:620)
    at com.lightcrafts.image.types.JPEGImageType.readMetadata(JPEGImageType.java:763)
    at com.lightcrafts.image.ImageInfo.getMetadata(ImageInfo.java:300)
    at com.lightcrafts.ui.metadata2.MetadataStack.setImage(MetadataStack.java:49)
    at com.lightcrafts.ui.metadata2.MetadataStack.<init>(MetadataStack.java:34)
    at com.lightcrafts.ui.metadata2.MetadataScroll.setImage(MetadataScroll.java:55)
    at com.lightcrafts.app.ComboFrame.setImage(ComboFrame.java:410)
    at com.lightcrafts.app.ComboFrame.selectionChanged(ComboFrame.java:421)
    at com.lightcrafts.ui.browser.view.ImageBrowserMulticaster.selectionChanged(ImageBrowserMulticaster.java:41)
    at com.lightcrafts.ui.browser.view.ImageBrowserMulticaster.selectionChanged(ImageBrowserMulticaster.java:42)
    at com.lightcrafts.ui.browser.view.ImageBrowserMulticaster.selectionChanged(ImageBrowserMulticaster.java:42)
    at com.lightcrafts.ui.browser.view.ImageBrowserMulticaster.selectionChanged(ImageBrowserMulticaster.java:42)
    at com.lightcrafts.ui.browser.view.ImageBrowserMulticaster.selectionChanged(ImageBrowserMulticaster.java:42)
    at com.lightcrafts.ui.browser.view.ImageBrowserMulticaster.selectionChanged(ImageBrowserMulticaster.java:42)
    at com.lightcrafts.ui.browser.view.ImageBrowserMulticaster.selectionChanged(ImageBrowserMulticaster.java:42)
    at com.lightcrafts.ui.browser.view.ImageBrowserMulticaster.selectionChanged(ImageBrowserMulticaster.java:42)
    at com.lightcrafts.ui.browser.view.ImageBrowserMulticaster.selectionChanged(ImageBrowserMulticaster.java:42)
    at com.lightcrafts.ui.browser.view.ImageBrowserMulticaster.selectionChanged(ImageBrowserMulticaster.java:42)
    at com.lightcrafts.ui.browser.view.ImageBrowserMulticaster.selectionChanged(ImageBrowserMulticaster.java:42)
    at com.lightcrafts.ui.browser.view.ImageBrowserMulticaster.selectionChanged(ImageBrowserMulticaster.java:42)
    at com.lightcrafts.ui.browser.view.ImageBrowserMulticaster.selectionChanged(ImageBrowserMulticaster.java:42)
    at com.lightcrafts.ui.browser.view.ImageBrowserMulticaster.selectionChanged(ImageBrowserMulticaster.java:42)
    at com.lightcrafts.ui.browser.view.ImageBrowserMulticaster.selectionChanged(ImageBrowserMulticaster.java:42)
    at com.lightcrafts.ui.browser.view.ImageBrowserMulticaster.selectionChanged(ImageBrowserMulticaster.java:42)
    at com.lightcrafts.ui.browser.view.ImageBrowserMulticaster.selectionChanged(ImageBrowserMulticaster.java:42)
    at com.lightcrafts.ui.browser.view.ImageBrowserMulticaster.selectionChanged(ImageBrowserMulticaster.java:42)
    at com.lightcrafts.ui.browser.view.ImageBrowserMulticaster.selectionChanged(ImageBrowserMulticaster.java:42)
    at com.lightcrafts.ui.browser.view.ImageBrowserMulticaster.selectionChanged(ImageBrowserMulticaster.java:42)
    at com.lightcrafts.ui.browser.view.ImageBrowserMulticaster.selectionChanged(ImageBrowserMulticaster.java:42)
    at com.lightcrafts.ui.browser.view.ImageBrowserMulticaster.selectionChanged(ImageBrowserMulticaster.java:42)
    at com.lightcrafts.ui.browser.view.ImageBrowserMulticaster.selectionChanged(ImageBrowserMulticaster.java:42)
    at com.lightcrafts.ui.browser.view.ImageBrowserMulticaster.selectionChanged(ImageBrowserMulticaster.java:42)
    at com.lightcrafts.ui.browser.view.ImageBrowserMulticaster.selectionChanged(ImageBrowserMulticaster.java:42)
    at com.lightcrafts.ui.browser.view.ImageBrowserMulticaster.selectionChanged(ImageBrowserMulticaster.java:42)
    at com.lightcrafts.ui.browser.view.ImageBrowserMulticaster.selectionChanged(ImageBrowserMulticaster.java:42)
    at com.lightcrafts.ui.browser.view.AbstractImageBrowser.notifySelectionChanged(AbstractImageBrowser.java:852)
    at com.lightcrafts.ui.browser.view.ImageBrowserSelectionModel.setLeadSelected(ImageBrowserSelectionModel.java:27)
    at com.lightcrafts.ui.browser.view.AbstractImageBrowser.setSelectedFiles(AbstractImageBrowser.java:514)
    at com.lightcrafts.app.ComboFrame$8.run(ComboFrame.java:1122)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
    at java.awt.EventQueue.access$200(EventQueue.java:103)
    at java.awt.EventQueue$3.run(EventQueue.java:694)
    at java.awt.EventQueue$3.run(EventQueue.java:692)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)

Git bisect gives a2d5f99ed0bb95eadbef98bba03f62e0e5633704 (Fixed #119) as the commit that is causing the problem but the stack trace that I am getting from is different:

java.lang.NoClassDefFoundError: javax/help/HelpSetException
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:190)
    at com.lightcrafts.platform.Platform.<clinit>(Platform.java:405)
    at com.lightcrafts.platform.linux.LinuxLauncher.main(LinuxLauncher.java:35)
Caused by: java.lang.ClassNotFoundException: javax.help.HelpSetException
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    ... 4 more
